# Generated by Django 5.1.3 on 2024-12-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
                ('dept_loc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(max_length=20, null=True)),
                ('mgr', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.depertment')),
            ],
        ),
    ]
