# Generated by Django 5.1.3 on 2024-12-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depertment',
            name='dept_loc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='depertment',
            name='dept_name',
            field=models.CharField(max_length=50),
        ),
    ]
